name: space-age
version: 1.1.0.5

dependencies:
  - base

library:
  # this is commented out, since otherwise the Cabal file is broken
  # exposed-modules: SpaceAge, Alternative
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - space-age
      - hspec

benchmarks:
  bench:
    main: bench.hs
    source-dirs: bench
    dependencies:
      - space-age
      - criterion
    ghc-options: -O2